name: Deploy Hugo site to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_GOOGLEANALYTICS: ${{ secrets.GA4_ID }}
      HUGO_ENVIRONMENT: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.2'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: devseunggwan/devseunggwan.github.io
          publish_branch: main
          publish_dir: ./public
